name: Ensure Container Runtime
description: Install and configure Podman for CI jobs.
runs:
  using: composite
  steps:
    - name: Ensure container runtime
      shell: bash
      run: |
        set -euo pipefail

        # 1. Ensure Podman and its core dependencies are installed
        if ! command -v podman >/dev/null 2>&1; then
          echo "Installing Podman and dependencies..."
          sudo apt-get update
          sudo apt-get install -y podman dbus-user-session slirp4netns
        fi

        # 2. Determine the best runtime directory
        USER_ID=$(id -u)
        if [[ -d "/run/user/${USER_ID}" ]]; then
          export XDG_RUNTIME_DIR="/run/user/${USER_ID}"
        else
          export XDG_RUNTIME_DIR="/tmp/podman-run-${USER_ID}"
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"
        fi

        # 3. Configure D-Bus address for netavark/aardvark-dns
        if [[ -S "${XDG_RUNTIME_DIR}/bus" ]]; then
          export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
        else
          export DBUS_SESSION_BUS_ADDRESS=""
        fi

        # 4. Recover from potential corrupted state
        echo "Migrating Podman system state..."
        podman system migrate || true

        # 5. Start podman system service if socket is missing or unresponsive
        SOCKET_PATH="${XDG_RUNTIME_DIR}/podman/podman.sock"
        SERVICE_NEEDED=0
        if [[ ! -S "$SOCKET_PATH" ]]; then
          SERVICE_NEEDED=1
        elif ! podman info >/dev/null 2>&1; then
          echo "Podman socket exists but is unresponsive. Removing stale socket."
          rm -f "$SOCKET_PATH"
          SERVICE_NEEDED=1
        fi

        if [[ "$SERVICE_NEEDED" -eq 1 ]]; then
          echo "Starting podman system service..."
          mkdir -p "$(dirname "$SOCKET_PATH")"
          podman system service --time=0 "unix://${SOCKET_PATH}" &

          # Wait for socket
          for i in {1..60}; do
            [[ -S "$SOCKET_PATH" ]] && podman info >/dev/null 2>&1 && break
            echo "Waiting for podman socket... ($i)"
            sleep 0.5
          done
        fi

        # 6. Export variables for subsequent steps
        {
          echo "XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}"
          echo "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}"
          echo "DOCKER_HOST=unix://${SOCKET_PATH}"
        } >> "${GITHUB_ENV}"

        # 7. Final verification and pre-pull images
        echo "Verifying Podman..."
        # Use the socket path explicitly to avoid environment propagation issues in the current step
        export DOCKER_HOST="unix://${SOCKET_PATH}"
        podman info > /dev/null || { echo "Podman info failed, trying system migrate..."; podman system migrate; podman info; }

        echo "Pre-pulling Postgres and Vault images..."
        podman pull postgres:18 || true
        podman pull hashicorp/vault:1.17.3 || true
